//
// JobsAPI.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation



open class JobsAPI {
    /**
     Get Jobs
     
     - parameter description: (query) job description 
     - parameter page: (query) Paging (optional)
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - parameter completion: completion handler to receive the data and the error objects
     */
    open class func getJobs(description: String, page: Int? = nil, apiResponseQueue: DispatchQueue = OpenAPIClientAPI.apiResponseQueue, completion: @escaping ((_ data: [Job]?,_ error: Error?) -> Void)) {
        getJobsWithRequestBuilder(description: description, page: page).execute(apiResponseQueue) { result -> Void in
            switch result {
            case let .success(response):
                completion(response.body, nil)
            case let .failure(error):
                completion(nil, error)
            }
        }
    }

    /**
     Get Jobs
     - GET /positions.json
     - parameter description: (query) job description 
     - parameter page: (query) Paging (optional)
     - returns: RequestBuilder<[Job]> 
     */
    open class func getJobsWithRequestBuilder(description: String, page: Int? = nil) -> RequestBuilder<[Job]> {
        let path = "/positions.json"
        let URLString = OpenAPIClientAPI.jobBasePath + path
        let parameters: [String:Any]? = nil
        
        var url = URLComponents(string: URLString)
        url?.queryItems = APIHelper.mapValuesToQueryItems([
            "description": description.encodeToJSON(), 
            "page": page?.encodeToJSON()
        ])

        let requestBuilder: RequestBuilder<[Job]>.Type = OpenAPIClientAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "GET", URLString: (url?.string ?? URLString), parameters: parameters, isBody: false)
    }

}
